### ISSUE TITLE
7.10 support

### ISSUE THREAD

**Issue by StephenOTT** [SebastianStamm/camunda-night-mode#1]
Any idea what updates are needed for 7.10?  looking at springboot as well

**Comment by SebastianStamm** [comment]
Since this is only a frontend-only plugin, it is completely independent from springboot. You only have to adjust the config.js as described in the readme.

Did you try it with 7.10? Are there any errors?

**Comment by StephenOTT** [comment]
Does this go into the Plugins folder of 7.10? or in the app folder?

**Comment by SebastianStamm** [comment]
I hope you got it to run :) If you still have any questions or comments, feel free to reopen this issue
